sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version


    #安装任务一需要使用的工具imagemagick
    - sudo apt-get install imagemagick
    - sudo apt install ghostscript


    #下载任务2-2需要使用的文件
    - wget "https://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv"
    - wget "https://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
    - sudo apt install p7zip-full
    - 7z x web_log.tsv.7z


script:

#任务一
  - bash test.sh
  - bash lab4/image-process.sh -h
  - bash lab4/image-process.sh -f image/ -i 50
  - bash lab4/image-process.sh -f image/ -C 50
  - bash lab4/image-process.sh -f image/ -w "suancaiji"
  - bash lab4/image-process.sh -f image/ -s "pro_rename"
  - bash lab4/image-process.sh -f image/ -p "pre_rename"

#任务二
  - bash lab4/worldcup.sh

#任务三
  - bash lab4/web.sh -h
  - bash lab4/web.sh -a
  - bash lab4/web.sh -b
  - bash lab4/web.sh -c
  - bash lab4/web.sh -d
  - bash lab4/web.sh -e
  - bash lab4/web.sh -f /





after_script:
  - /usr/bin/shellcheck lab4/test.sh
  - /usr/bin/shellcheck lab4/image.sh
  - /usr/bin/shellcheck lab4/worldcup.sh
  - /usr/bin/shellcheck lab4/web_log.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
          
